version: '3'
services:

    # Laravel
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: my-laravel-app
        container_name: my-laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: my-laravel-app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    # MySql service
    db:
        image: mysql:8
        container_name: my-laravel-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "13306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
        volumes:
            - ./database/mysql:/var/lib/mysql
        networks:
            - app-network

    # Nginx Service
    web:
        image: 'nginx:alpine'
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - ./database/mongodb/db:/data/db
            - ./database/mongodb/dev.archive:/Databases/dev.archive
            - ./database/mongodb/production:/Databases/production
        command: [ --auth ]


    mongo-express:
        image: mongo-express:latest
        container_name: mexpress
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
            - ME_CONFIG_BASICAUTH_USERNAME=mexpress
            - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
        links:
            - mongo
        restart: unless-stopped
        ports:
            - "8081:8081"

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
